<a href="https://colab.research.google.com/github/LMORALESDEV/PYTHON-ITLA/blob/main/0502_Introducci%C3%B3n_a_las_Estructuras_de_Datos_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Estructuras de Datos: Listas

En Python, hay varias funciones que se pueden usar para manipular listas. Algunas de las funciones más comunes incluyen:

**append():** Agrega un elemento al final de la lista.


In [ ]:
mi_lista = [1, 2, 3,4]
mi_lista.append(6)
print(mi_lista)


[1, 2, 3, 4, 6]


**extend():** Agrega los elementos de otra lista al final de la lista.

In [ ]:
mi_lista = [1, 2, 3]
otra_lista = [4, 5, 6]
mi_lista.extend(otra_lista)
print(mi_lista)


[1, 2, 3, 4, 5, 6]


**insert():** Inserta un elemento en una posición específica de la lista.


In [ ]:
mi_lista = [1, 2, 3]
mi_lista.insert(1, 4) #Posicion, Valor
print(mi_lista)


[1, 4, 2, 3]


**remove():** Elimina el primer elemento de la lista que coincide con el valor especificado.

In [ ]:
mi_lista = [1, 2, 3, 2]
mi_lista.remove(2)
print(mi_lista)


[1, 3, 2]


**pop():** Elimina y devuelve el elemento en la posición especificada. Si no se especifica ninguna posición, elimina y devuelve el último elemento de la lista.

In [ ]:
mi_lista = [1, 2, 3]
eliminado = mi_lista.pop(1) #Posicion
print(mi_lista)
print(eliminado)

[1, 3]
2


**index():** Devuelve la posición de la primera aparición del valor especificado en la lista.

In [ ]:
mi_lista = [1, 2, 3, 2]
posicion = mi_lista.index(2)
print(posicion)


1


**count():** Devuelve el número de veces que aparece un valor en la lista.

In [ ]:
mi_lista = [1, 2, 3, 2]
conteo = mi_lista.count(2)
print(conteo)


2


**sort():** Ordena los elementos de la lista en orden ascendente.

In [ ]:
#Ascendente
mi_lista = [3, 1, 2,5,7,0]
mi_lista.sort()
print(mi_lista)

#Descendente
mi_lista = [3, 1, 2, 5, 7, 0]
mi_lista.sort(reverse=False)
print(mi_lista)


[0, 1, 2, 3, 5, 7]
[0, 1, 2, 3, 5, 7]


**reverse():** Invierte la posicion de los elementos en la lista.

In [ ]:
mi_lista = [3,1,2,5,7,0]
mi_lista.reverse()
print(mi_lista) #Espejo


[0, 7, 5, 2, 1, 3]


**clear():** Elimina todos los elementos de la lista.

In [ ]:
mi_lista = [1, 2, 3]
mi_lista.clear()
print(mi_lista)

[]


**copy():** Devuelve una copia superficial de la lista

In [ ]:
mi_lista = [1, 2, 3]
otra_lista = mi_lista.copy()
print(otra_lista)


[1, 2, 3]


**len():** Devuelve el número de elementos en la lista.

In [ ]:
mi_lista = [1, 2, 3]
longitud = len(mi_lista)
print(longitud)


3


**max():** Devuelve el elemento máximo en la lista.

In [ ]:
mi_lista = ['mama', 'b', 'c']
#mi_lista2 = [5,10,15,8,0,78]
maximo = max(mi_lista)
print(maximo)


mama


**min():** Devuelve el elemento mínimo en la lista.

In [ ]:
mi_lista = [1, 2, 3]
minimo = min(mi_lista)
print(minimo)


1


**sum():** Devuelve la suma de todos los elementos en la lista.

In [ ]:
mi_lista = [1, 2, 3]
suma = sum(mi_lista)

suma = mi_lista[0] + mi_lista[2]

print(suma)

6


**any():** Devuelve **True** si al menos uno de los elementos en la lista es verdadero. De lo contrario, devuelve **False**.

In [ ]:
mi_lista = [0, False, "", None]
resultado = any(mi_lista)
print(resultado) #False

mi_lista = [0, False, "", None, 1]
resultado = any(mi_lista)
print(resultado) #True

False
True


**all():** Devuelve **True** si todos los elementos en la lista son verdaderos. De lo contrario, devuelve **False**.

In [ ]:

mi_lista = [2, True, "Hola"]
resultado = all(mi_lista)
print(resultado) #True

mi_lista = [1, True, "Hola", False]
resultado = all(mi_lista)
print(resultado) #False

True
False


**filter():** Crea una nueva lista con los elementos de la lista original que cumplen una condición especificada.

**NOTA**: La palabra clave "**lambda**" se usa para definir una función anónima, es decir, una función sin nombre

In [ ]:
mi_lista = [1, 2, 3, 4, 5]
#Paridad utilizando el modulo %
nueva_lista = list(filter(lambda x: x % 2 == 0, mi_lista))
print(nueva_lista)



[2, 4]


**map():** Crea una nueva lista aplicando una función a cada elemento de la lista original.

In [ ]:
mi_lista = [1, 2, 3, 4, 5]
nueva_lista = list(map(lambda x: x ** 2 , mi_lista))
print(nueva_lista)


[1, 4, 9, 16, 25]


**reduce():** Aplica una función a los primeros dos elementos de la lista, luego aplica la misma función al resultado y al siguiente elemento, y así sucesivamente hasta que se procesen todos los elementos de la lista. Devuelve el resultado final.

**Nota**: reduce() se encuentra en el módulo functools en Python 3, por lo que se debe importar antes de usarlo.

In [ ]:
from functools import reduce


mi_lista = [1, 2, 3, 4, 5]
resultado = reduce(lambda x, y, z: x * y, mi_lista)
print(resultado) #Resultado: 15


120


#Diccionarios en Python

* Un diccionario es una estructura de datos que permite almacenar cualquier tipo de información, desde cadenas de texto o caracteres hasta números enteros, con decimales, listas e incluso otros diccionarios. Los datos se encuentran ordenados utilizando una clave única para cada uno de ellos, lo que permite localizar cada uno de los datos de una forma muy rápida.

* Los diccionarios Python son mutables, esto quiere decir que no tienen un tamaño predefinido y que su contenido aumenta o disminuye según las necesidades de la aplicación. Todos los datos son también modificables, es decir, se puede añadir, modificar, eliminar y consultar todos los datos de una manera sencilla y rápida.


###Ejemplos de manipulación de diccionarios

Agregar un elemento al diccionario:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
mi_diccionario["ciudad"] = "Madrid"
print(mi_diccionario)


{'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}


Eliminar un elemento del diccionario:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
del mi_diccionario["edad"]
print(mi_diccionario) lista.

{'nombre': 'Juan'}


Obtener el valor de una clave del diccionario:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
print(mi_diccionario["edad"])

25


Actualizar un valor de una clave del diccionario:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
mi_diccionario["edad"] = 30
print(mi_diccionario)

{'nombre': 'Juan', 'edad': 30}


Verificar si una clave existe en el diccionario:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25, "ciudad": "Madrid"}

#Utilizando la expresion "in"
if "pais" in mi_diccionario:
    print("La clave 'ciudad' existe en el diccionario")
else:
    print("La clave 'ciudad' no existe en el diccionario")


La clave 'ciudad' no existe en el diccionario


Obtener todas las claves del diccionario, utilizando la propiedad "keys":

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
print(mi_diccionario.keys())

dict_keys(['nombre', 'edad'])


Obtener todos los valores del diccionario, utilizando la propiedad "values":

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
print(mi_diccionario.values())

dict_values(['Juan', 25])


Obtener todas las parejas clave-valor del diccionario, utilizando la propiedad "items":

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
print(mi_diccionario.items())

dict_items([('nombre', 'Juan'), ('edad', 25)])


Copiar un diccionario, utilizando la propiedad "copy":

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
nuevo_diccionario = mi_diccionario.copy()
print(nuevo_diccionario)


{'nombre': 'Juan', 'edad': 25}


Vaciar un diccionario:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
mi_diccionario.clear()
print(mi_diccionario)

{}


Obtener un valor predeterminado si la clave no existe:

In [ ]:
mi_diccionario = {"nombre": "Juan", "edad": 25}
valor_predeterminado = mi_diccionario.get("ciudad", "Barcelona")
print(valor_predeterminado)


Barcelona


##Introduccion a NumPy, para manipular listas

**NumPy (Numerical Python)** es una biblioteca de Python que se utiliza para realizar cálculos numéricos en matrices y matrices multidimensionales. Proporciona una amplia gama de funciones matemáticas y operaciones que son útiles en aplicaciones científicas y de ingeniería.

In [ ]:
#Importamos la libreria numpy
import numpy as np

Crear una matriz a partir de una lista de Python:

In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5]
matriz = np.array(lista)
print(matriz)


[1 2 3 4 5]


Crear una matriz multidimensional a partir de una lista de listas:

In [ ]:
import numpy as np

tabla = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(tabla)
print(matriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Realizar una operación matemática en una matriz de NumPy creada a partir de una lista:

In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5]
matriz = np.array(lista)

#Multiplicar cada elemento de la matriz por 2
resultado = matriz * 2
print(resultado)


[ 2  4  6  8 10]


Obtener el valor **máximo** y **mínimo** de una matriz de NumPy creada a partir de una lista:

In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5]
matriz = np.array(lista)

#Obtener el valor máximo y mínimo de la matriz
maximo = np.max(matriz)
minimo = np.min(matriz)

print("Valor máximo:", maximo)
print("Valor mínimo:", minimo)


Valor máximo: 5
Valor mínimo: 1


Crear una matriz con valores aleatorios de una lista de tamaño especificado:

In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
tamano = int(input("De que tamaño desea la lista? "))
matriz = np.array(lista)

#Crear una matriz de tamaño 3 con valores aleatorios de la lista
matriz_aleatoria = np.random.choice(matriz, size=(tamano))
print(matriz_aleatoria)

De que tamaño desea la lista? 15
[ 3  9  8  1  4  8  1 12  6  6 10 13 10  8  9]


##Filtrando valores de una lista usando NumPy

Es posible filtrar los valores de una lista utilizando **NumPy** de varias maneras. Una forma común es utilizar la **indexación booleana**, que te permite seleccionar solo los elementos de una matriz que cumplan con una determinada condición.

Filtrar valores **mayores** a un numero x:

In [ ]:
import numpy as np

#Crear una lista de números aleatorios
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Convertir la lista en una matriz de NumPy
matriz = np.array(lista)

#Crear una variable para filtrar los valores mayores que 5
filtro =  matriz < 6
filtro2 =  matriz > 6

#Filtrar los valores mayores que 5
resultado = matriz[filtro2]

#Imprimir el resultado
print(resultado)


[ 7  8  9 10]


Filtrar valores menores que un número específico:

In [ ]:
import numpy as np

#Crear una lista de números aleatorios
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Convertir la lista en una matriz de NumPy
matriz = np.array(lista)

#Filtrar los valores menores que 5
resultado = matriz[matriz < 5]

#Imprimir el resultado
print(resultado)

Generando la media o el valor promedio de una lista:

In [ ]:
import numpy as np

#Crear una lista de números aleatorios
#lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista = [80,50,10,5.5,100, 9, 10]

#Convertir la lista en una matriz de NumPy
matriz = np.array(lista)

#Filtrar los valores menores que 5
resultado = np.mean(matriz)

#Imprimir el resultado
print(resultado)


37.785714285714285


Filtrar valores entre dos números específicos:

In [ ]:
import numpy as np

#Crear una lista de números aleatorios
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Convertir la lista en una matriz de NumPy
matriz = np.array(lista)

#Filtrar los valores entre 3 y 7
resultado = matriz[(matriz > 3) & (matriz < 7)]

#Imprimir el resultado
print(resultado)


[4 5 6]


Filtrar valores que cumplen una condición específica utilizando una función de NumPy:

In [ ]:
import numpy as np

#Crear una lista de números aleatorios
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Convertir la lista en una matriz de NumPy
matriz = np.array(lista)

#Filtrar los valores pares utilizando mod
resultado = matriz[np.mod(matriz, 5) == 0]

#Imprimir el resultado
print(resultado)


[ 5 10]


En este ejemplo, utilizamos la función **np.mod()** de NumPy para obtener el resto de la división de cada elemento de la matriz por 2. Luego, utilizamos la indexación booleana para filtrar los valores de la matriz que tienen un resto de división igual a 0, lo que significa que son pares.

##Otras funciones

NumPy es una librería muy grande con muchas funciones y herramientas útiles para trabajar con matrices y arreglos en Python. Algunas de las funciones útiles de NumPy:

* numpy.array(): Crea una matriz de NumPy a partir de una lista o tupla de valores.
* numpy.zeros(): Crea una matriz de NumPy llena de ceros.
* numpy.ones(): Crea una matriz de NumPy llena de unos.
* numpy.full(): Crea una matriz de NumPy llena de un valor específico.
* etc..etc..
